language: csharp
solution: Strados.Obd.sln
install:
  - nuget restore Strados.Obd.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Strados.Obd.sln
#  - mono mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./Strados.Tests/bin/Release/Strados.Tests.dll